## Challenge - Joining on multiple tables
## Write SQL queries to perform the following tasks using the Sakila database:
## 1. List the number of films per category.
select c.name as category_name, count(film_id) as num_films
from category as c
inner join film_category f on f.category_id = c.category_id
group by category_name
order by num_films desc;

## 2. Retrieve the store ID, city, and country for each store.
select s.store_id,  c.city, co.country
from store s
left join address a on  s.address_id = a.address_id
left join city c on a.city_id = c.city_id
left join country co on c.country_id = co.country_id;	

## 3. Calculate the total revenue generated by each store in dollars.
select *
from store
   
## 4. Determine the average running time of films for each category. 
## Bonus:
## Identify the film categories with the longest average running time.
## Display the top 10 most frequently rented movies in descending order.
## Determine if "Academy Dinosaur" can be rented from Store 1.
## Provide a list of all distinct film titles, along with their availability status in the inventory.
## Include a column indicating whether each title is 'Available' or 'NOT available.' 
## Note that there are 42 titles that are not in the inventory, and this information can be obtained using a CASE statement combined with IFNULL."